# Generated by Django 3.1.3 on 2020-11-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20201121_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/'),
        ),
    ]
