# Generated by Django 3.1.3 on 2020-11-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20201123_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
