# Generated by Django 3.1.3 on 2020-11-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_auto_20201123_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
